<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Student extends Model
{
    use HasUuids;

    public $incrementing = false;

    protected $keyType = 'string';

    protected $table = 'students';

    // display_id is generated by a DB trigger (trg_student_display_id) when
    // null — never set it from application code.
    protected $fillable = [
        'org_code',
        'name',
        'batch',
        'course_id',
        'duration',
        'created_by',
    ];

    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class, 'org_code', 'code');
    }

    public function course(): BelongsTo
    {
        return $this->belongsTo(Course::class, 'course_id');
    }

    public function attendance(): HasMany
    {
        return $this->hasMany(Attendance::class, 'student_id');
    }

    public function gtAssessments(): HasMany
    {
        return $this->hasMany(GtAssessment::class, 'student_id');
    }

    public function gaCodingPractice(): HasMany
    {
        return $this->hasMany(GaCodingPractice::class, 'student_id');
    }

    public function gaFinalExams(): HasMany
    {
        return $this->hasMany(GaFinalExam::class, 'student_id');
    }
}
